import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const sql = fs.readFileSync('supabase/migrations/20260827140000_product_so_reservation_dc_batch_allocation.sql','utf8');
const productionMigration = fs.readFileSync('supabase/migrations/20260827150000_migrate_safe_product_reservations.sql','utf8');
const finalHoldMigration = fs.readFileSync('supabase/migrations/20260827170000_finalize_hold_product_reservations.sql','utf8');
const dcReapprovalGuardMigration = fs.readFileSync('supabase/migrations/20260827180000_block_reapproval_of_reversed_delivery_challan.sql','utf8');
const dcUi = fs.readFileSync('src/pages/DeliveryChallan.tsx','utf8');
const plan = JSON.parse(fs.readFileSync('audits/inventory/product-reservation-migration-plan-20260827.json','utf8'));

class Model {
  constructor(stock) { this.stock={...stock}; this.orders=new Map(); this.allocations=new Set(); }
  atp(product,exclude) { return (this.stock[product]||0)-[...this.orders.entries()].reduce((n,[id,o])=>n+(id===exclude||!o.active?0:o.reserved),0); }
  approve(id,product,ordered,delivered=0) { const old=this.orders.get(id); const required=ordered-delivered; if(required<0) throw Error('over'); if(required>this.atp(product,id)) throw Error('atp'); this.orders.set(id,{product,ordered,delivered,reserved:required,active:true}); return old?required-old.reserved:required; }
  edit(id,ordered) { const o=this.orders.get(id); return this.approve(id,o.product,ordered,o.delivered); }
  release(id) { const o=this.orders.get(id); if(!o.active) return 0; const q=o.reserved;o.active=false;o.reserved=0;return q; }
  deliver(id,key,batch,qty) { const o=this.orders.get(id); if(this.allocations.has(key)) throw Error('duplicate'); if(!o.active||qty>o.reserved) throw Error('reservation'); if((this.stock[batch]||0)<qty) throw Error('stock'); o.reserved-=qty;o.delivered+=qty;this.stock[batch]-=qty;this.allocations.add(key);return o; }
}

test('A/B approval and competing ATP do not change physical stock',()=>{const m=new Model({p:1000});assert.equal(m.approve('a','p',600),600);assert.throws(()=>m.approve('b','p',401),/atp/);assert.equal(m.stock.p,1000);assert.equal(m.approve('b','p',400),400);});
test('C/D/E edit increase decrease and partial delivery use deltas',()=>{const m=new Model({p:1000,b:1000});m.approve('a','p',500);assert.equal(m.edit('a',700),200);assert.equal(m.edit('a',500),-200);m.deliver('a','d1','b',300);assert.equal(m.edit('a',700),200);assert.equal(m.edit('a',500),-200);assert.equal(m.orders.get('a').reserved,200);});
test('F/G/H/I/J/W rejection cancellation void and reapproval are idempotent',()=>{const m=new Model({p:1000});m.approve('a','p',500);assert.equal(m.release('a'),500);assert.equal(m.release('a'),0);m.approve('a','p',500);assert.equal(m.orders.get('a').reserved,500);m.release('a');m.approve('a','p',700);assert.equal(m.orders.get('a').reserved,700);});
test('K/L/M multiple DCs, partial DC and multiple batches reconcile',()=>{const m=new Model({p:1000,a:200,b:300});m.approve('so','p',500);m.deliver('so','d1','a',200);m.deliver('so','d2','b',300);assert.deepEqual(m.orders.get('so'),{product:'p',ordered:500,delivered:500,reserved:0,active:true});});
test('Q/R/S/T/U/V invalid, insufficient, duplicate and rollback conditions fail safely',()=>{const m=new Model({p:500,a:200});m.approve('so','p',500);const before=JSON.stringify(m);assert.throws(()=>m.deliver('so','bad','a',300),/stock/);assert.equal(JSON.stringify(m),before);m.deliver('so','one','a',100);assert.throws(()=>m.deliver('so','one','a',1),/duplicate/);assert.throws(()=>m.deliver('so','two','a',101),/stock/);});
test('N/O/P/X architecture supports multiple lines, FEFO suggestion, alternate batches and audit history',()=>{assert.match(sql,/so_product_reservation_events/);assert.match(sql,/dc_batch_allocations/);assert.match(sql,/expiry_date/);assert.match(dcUi,/const fifoBatch = productBatches\[0\]/);assert.doesNotMatch(sql,/INSERT INTO public\.stock_reservations/);});
test('constraints prevent duplicate active reservation, negatives and over-delivery',()=>{assert.match(sql,/uq_so_product_reservation_active_item/);assert.match(sql,/reserved_quantity > 0/);assert.match(sql,/current_stock>=v\.quantity/);assert.match(sql,/DC quantity exceeds remaining SO product reservation/);});
test('concurrent ATP, lifecycle entry points and approval are database-guarded',()=>{assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/trg_reconcile_active_so_item_v2/);assert.match(sql,/fn_auto_rereserve_on_batch_arrival[\s\S]*RETURN NEW/);assert.match(sql,/Cannot approve Delivery Challan % without items/);assert.match(sql,/REVOKE ALL ON FUNCTION[\s\S]*approve_sales_order_product_reservation_v2/);});
test('ATP remains invariant while ambiguous legacy reservations are held',()=>{assert.match(sql,/FROM public\.stock_reservations sr/);assert.match(sql,/sr\.status='active' AND NOT sr\.is_released/);assert.match(sql,/sr\.id=ANY\(migrated\.legacy_reservation_ids\)/);});
test('pending DC creation does not mark the SO delivered',()=>{assert.doesNotMatch(dcUi,/rpc\('update_so_delivered_quantity_atomic'/);assert.match(dcUi,/Pending DCs are not deliveries/);});
test('reservation query failure is explicit and never rendered as zero',()=>{assert.match(dcUi,/if \(reservationsResult\.error\) throw reservationsResult\.error/);assert.match(dcUi,/Unavailable \(reservation query failed\)/);assert.match(dcUi,/soReservationLoadState === 'error'/);assert.doesNotMatch(dcUi,/soReservations\.get\(source\.id\) \|\| 0/);});
test('current 0033/0034 cases and third row are explicit and held',()=>{const held=plan.reservations.filter(r=>r.migration_action==='HOLD_AMBIGUOUS_PENDING_DC');assert.equal(held.length,3);assert.deepEqual([...new Set(held.map(r=>r.so))],['SO-2026-0033','SO-2026-0034']);assert.equal(plan.missing_third_ambiguous_record,'f7428c8d-68fd-473f-9d14-ce5b77a98768');});
test('all 19 safe rows are exactly represented and history is excluded',()=>{const safe=plan.reservations.filter(r=>r.migration_action==='CONSOLIDATE_TO_PRODUCT_RESERVATION');assert.equal(safe.length,19);assert.equal(safe.reduce((n,r)=>n+r.current_quantity,0),15630);assert.equal(plan.summary.historical_rows,126);});
test('migration preview is quantity-neutral',()=>{const safe=plan.reservations.filter(r=>r.migration_action==='CONSOLIDATE_TO_PRODUCT_RESERVATION');const holds=plan.reservations.filter(r=>r.migration_action==='HOLD_AMBIGUOUS_PENDING_DC');const safeByItem=new Map();for(const row of safe)safeByItem.set(row.so_item_id,(safeByItem.get(row.so_item_id)||0)+row.current_quantity);for(const row of safe)assert.equal(safeByItem.get(row.so_item_id),row.proposed_product_level_reservation);assert.equal(safe.reduce((n,r)=>n+r.current_quantity,0)+holds.reduce((n,r)=>n+r.current_quantity,0),16630);assert.deepEqual(plan.proof_totals,{physical_stock_delta:0,delivered_quantity_delta:0,active_commitment_before:16630,active_commitment_after:16630,atp_delta:0,outstanding_so_quantity_delta:0,pending_dc_quantity_delta:0});});
test('authorized production migration is exact, atomic and HOLD-safe',()=>{const safeIds=plan.reservations.filter(r=>r.migration_action==='CONSOLIDATE_TO_PRODUCT_RESERVATION').map(r=>r.reservation_id);const holdIds=plan.reservations.filter(r=>r.migration_action==='HOLD_AMBIGUOUS_PENDING_DC').map(r=>r.reservation_id);for(const id of safeIds)assert.match(productionMigration,new RegExp(id));for(const id of holdIds)assert.match(productionMigration,new RegExp(id));assert.match(productionMigration,/BEGIN;[\s\S]*COMMIT;/);assert.match(productionMigration,/v_count<>19 OR v_quantity<>15630/);assert.match(productionMigration,/to_jsonb\(sr\)<>b\.row_fingerprint/);assert.match(productionMigration,/RAISE EXCEPTION 'ATP changed'/);assert.doesNotMatch(productionMigration,/post_inventory_movement/);assert.doesNotMatch(productionMigration,/UPDATE public\.batches/);assert.doesNotMatch(productionMigration,/UPDATE public\.sales_order_items/);assert.doesNotMatch(productionMigration,/UPDATE public\.delivery_challans/);});
test('final HOLD conversion is exact, history-preserving and quantity-neutral',()=>{for(const id of ['b45e28c8-3a68-4398-ae2f-97b4b767bd78','f7428c8d-68fd-473f-9d14-ce5b77a98768','fcfc7045-b456-40df-b897-d8e7f6b066e1'])assert.match(finalHoldMigration,new RegExp(id));assert.match(finalHoldMigration,/active_legacy_count FROM _final_before\)<>3/);assert.match(finalHoldMigration,/active_legacy_quantity FROM _final_before\)<>1000/);assert.match(finalHoldMigration,/Final conversion of verified HOLD legacy reservations/);assert.match(finalHoldMigration,/UPDATE public\.delivery_challan_items[\s\S]*sales_order_item_id/);assert.match(finalHoldMigration,/status='released',is_released=true/);assert.match(finalHoldMigration,/RAISE EXCEPTION 'Physical stock changed'/);assert.match(finalHoldMigration,/RAISE EXCEPTION 'SO ordered or delivered quantity changed'/);assert.match(finalHoldMigration,/RAISE EXCEPTION 'An inventory movement was created'/);assert.match(finalHoldMigration,/RAISE EXCEPTION 'Total active commitment changed'/);assert.doesNotMatch(finalHoldMigration,/UPDATE public\.batches/);assert.doesNotMatch(finalHoldMigration,/post_inventory_movement/);assert.doesNotMatch(finalHoldMigration,/UPDATE public\.sales_order_items/);assert.doesNotMatch(finalHoldMigration,/UPDATE public\.delivery_challans/);});
test('reversed Delivery Challans cannot be re-approved',()=>{assert.match(dcReapprovalGuardMigration,/OLD\.approval_status IN \('rejected','cancelled'\)/);assert.match(dcReapprovalGuardMigration,/cannot be re-approved/);assert.match(dcReapprovalGuardMigration,/consume_so_product_reservation_v2/);assert.match(dcReapprovalGuardMigration,/fn_recompute_so_delivered/);});

console.log('product reservation v2 regression matrix passed');
