-- Attribute PPh to the actual supplier-payment month.  Until a payment is
-- linked, the expense due date is the expected withholding period.  This is
-- derived from existing payment links; no register rows or new tables are
-- introduced.

CREATE OR REPLACE FUNCTION public.get_expense_pph_period_date(p_expense_id uuid)
RETURNS date
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT COALESCE(
    (
      SELECT MAX(payment_date)
      FROM (
        SELECT pv.voucher_date AS payment_date
        FROM public.voucher_allocations va
        JOIN public.payment_vouchers pv ON pv.id = va.payment_voucher_id
        WHERE va.finance_expense_id = fe.id
          AND COALESCE(va.payment_kind, 'supplier') = 'supplier'
          AND COALESCE(pv.is_posted, false) = true

        UNION ALL

        SELECT bsl.transaction_date
        FROM public.bank_statement_lines bsl
        WHERE bsl.matched_expense_id = fe.id
          AND COALESCE(bsl.payment_kind, 'supplier') = 'supplier'
      ) linked_supplier_payments
    ),
    fe.due_date,
    fe.expense_date
  )
  FROM public.finance_expenses fe
  WHERE fe.id = p_expense_id;
$$;

REVOKE ALL ON FUNCTION public.get_expense_pph_period_date(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_expense_pph_period_date(uuid) TO service_role;

CREATE OR REPLACE FUNCTION public.compute_period_ppn(p_period_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_period public.tax_periods%ROWTYPE;
  v_pph_total numeric(18,2);
BEGIN
  -- Keep the established PPN computation unchanged.
  PERFORM public.compute_period_ppn_pre_posted_register(p_period_id);

  SELECT * INTO v_period
  FROM public.tax_periods
  WHERE id = p_period_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tax period % not found', p_period_id;
  END IF;
  IF v_period.tax_type = 'PPN' THEN
    RETURN;
  END IF;

  SELECT
    COALESCE((
      SELECT SUM(fe.pph_amount)
      FROM public.finance_expenses fe
      LEFT JOIN public.tax_codes tc ON tc.id = fe.pph_code_id
      WHERE EXTRACT(YEAR FROM public.get_expense_pph_period_date(fe.id))::int = v_period.fiscal_year
        AND EXTRACT(MONTH FROM public.get_expense_pph_period_date(fe.id))::int = v_period.period_month
        AND fe.approval_status = 'approved'
        AND fe.pph_amount > 0
        AND COALESCE(fe.expense_category, '') NOT IN ('pib_import', 'pph_import')
        AND (v_period.tax_type = 'PPh_Unifikasi' OR tc.tax_type = v_period.tax_type)
    ), 0)
    + COALESCE((
      SELECT SUM(pv.pph_amount)
      FROM public.payment_vouchers pv
      LEFT JOIN public.tax_codes tc ON tc.id = pv.pph_code_id
      WHERE EXTRACT(YEAR FROM pv.voucher_date)::int = v_period.fiscal_year
        AND EXTRACT(MONTH FROM pv.voucher_date)::int = v_period.period_month
        AND COALESCE(pv.is_posted, false) = true
        AND pv.pph_amount > 0
        AND (v_period.tax_type = 'PPh_Unifikasi' OR tc.tax_type = v_period.tax_type)
    ), 0)
    + CASE WHEN v_period.tax_type IN ('PPh22', 'PPh_Unifikasi') THEN
      COALESCE((
        SELECT SUM(fe.pib_pph_amount)
        FROM public.finance_expenses fe
        WHERE fe.expense_category = 'pib_import'
          AND EXTRACT(YEAR FROM public.get_expense_pph_period_date(fe.id))::int = v_period.fiscal_year
          AND EXTRACT(MONTH FROM public.get_expense_pph_period_date(fe.id))::int = v_period.period_month
          AND fe.approval_status = 'approved'
          AND COALESCE(fe.pib_pph_amount, 0) > 0
      ), 0)
      + COALESCE((
        SELECT SUM(fe.amount)
        FROM public.finance_expenses fe
        WHERE fe.expense_category = 'pph_import'
          AND EXTRACT(YEAR FROM public.get_expense_pph_period_date(fe.id))::int = v_period.fiscal_year
          AND EXTRACT(MONTH FROM public.get_expense_pph_period_date(fe.id))::int = v_period.period_month
          AND fe.approval_status = 'approved'
          AND COALESCE(fe.amount, 0) > 0
      ), 0)
    ELSE 0 END
  INTO v_pph_total;

  UPDATE public.tax_periods
  SET pph_total = v_pph_total,
      updated_at = now()
  WHERE id = p_period_id;
END;
$$;

REVOKE ALL ON FUNCTION public.compute_period_ppn(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.compute_period_ppn(uuid) TO authenticated, service_role;

-- Ensure a destination period exists, then refresh every PPh type for the
-- affected month.  Due dates continue to be generated by upsert_tax_period()
-- from compute_tax_due_dates(), so they always follow the resulting period.
CREATE OR REPLACE FUNCTION public.recompute_pph_periods_for_date(p_date date)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_tax_type text;
  v_period_id uuid;
BEGIN
  IF p_date IS NULL THEN
    RETURN;
  END IF;

  FOREACH v_tax_type IN ARRAY ARRAY['PPh21', 'PPh22', 'PPh23', 'PPh4(2)']::text[]
  LOOP
    v_period_id := public.upsert_tax_period(
      EXTRACT(YEAR FROM p_date)::int,
      EXTRACT(MONTH FROM p_date)::int,
      v_tax_type
    );
    PERFORM public.compute_period_ppn(v_period_id);
  END LOOP;

  -- Keep a legacy stored consolidated period synchronized when one exists.
  FOR v_period_id IN
    SELECT id
    FROM public.tax_periods
    WHERE fiscal_year = EXTRACT(YEAR FROM p_date)::int
      AND period_month = EXTRACT(MONTH FROM p_date)::int
      AND tax_type = 'PPh_Unifikasi'
  LOOP
    PERFORM public.compute_period_ppn(v_period_id);
  END LOOP;
END;
$$;

REVOKE ALL ON FUNCTION public.recompute_pph_periods_for_date(date) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.recompute_pph_periods_for_date(date) TO service_role;

CREATE OR REPLACE FUNCTION public.trg_recompute_from_expense()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    IF COALESCE(OLD.pph_amount, 0) > 0
       OR COALESCE(OLD.pib_pph_amount, 0) > 0
       OR OLD.expense_category = 'pph_import' THEN
      PERFORM public.recompute_pph_periods_for_date(COALESCE(OLD.due_date, OLD.expense_date));
    END IF;
  ELSE
    IF COALESCE(NEW.pph_amount, 0) > 0
       OR COALESCE(NEW.pib_pph_amount, 0) > 0
       OR NEW.expense_category = 'pph_import' THEN
      PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(NEW.id));
    END IF;
    IF TG_OP = 'UPDATE' THEN
      IF COALESCE(OLD.pph_amount, 0) > 0
         OR COALESCE(OLD.pib_pph_amount, 0) > 0
         OR OLD.expense_category = 'pph_import' THEN
        PERFORM public.recompute_pph_periods_for_date(COALESCE(OLD.due_date, OLD.expense_date));
        PERFORM public.recompute_pph_periods_for_date(OLD.expense_date);
      END IF;
    END IF;
  END IF;
  RETURN NULL;
END;
$$;

-- This older trigger duplicated the expense-date refresh.  The canonical
-- trigger above now handles both the old and new attribution periods.
DROP TRIGGER IF EXISTS trg_recompute_finance_expense_period ON public.finance_expenses;

CREATE OR REPLACE FUNCTION public.trg_recompute_from_payment_voucher()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expense_id uuid;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') THEN
    IF COALESCE(OLD.pph_amount, 0) > 0 THEN
      PERFORM public.recompute_pph_periods_for_date(OLD.voucher_date);
    END IF;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') THEN
    IF COALESCE(NEW.pph_amount, 0) > 0 THEN
      PERFORM public.recompute_pph_periods_for_date(NEW.voucher_date);
    END IF;
  END IF;

  FOR v_expense_id IN
    SELECT DISTINCT va.finance_expense_id
    FROM public.voucher_allocations va
    JOIN public.finance_expenses fe ON fe.id = va.finance_expense_id
    WHERE va.payment_voucher_id = COALESCE(NEW.id, OLD.id)
      AND va.finance_expense_id IS NOT NULL
      AND (
        COALESCE(fe.pph_amount, 0) > 0
        OR COALESCE(fe.pib_pph_amount, 0) > 0
        OR fe.expense_category = 'pph_import'
      )
  LOOP
    PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(v_expense_id));
  END LOOP;
  RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.trg_recompute_pph_from_voucher_allocation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expense_id uuid;
  v_voucher_id uuid;
  v_date date;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') AND OLD.finance_expense_id IS NOT NULL THEN
    v_expense_id := OLD.finance_expense_id;
    PERFORM 1 FROM public.finance_expenses fe
    WHERE fe.id = v_expense_id
      AND (COALESCE(fe.pph_amount, 0) > 0 OR COALESCE(fe.pib_pph_amount, 0) > 0 OR fe.expense_category = 'pph_import');
    IF NOT FOUND THEN
      v_expense_id := NULL;
    END IF;
  END IF;
  IF TG_OP IN ('UPDATE', 'DELETE') AND v_expense_id IS NOT NULL THEN
    v_voucher_id := OLD.payment_voucher_id;
    SELECT voucher_date INTO v_date FROM public.payment_vouchers WHERE id = v_voucher_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
    PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(v_expense_id));
    SELECT COALESCE(due_date, expense_date) INTO v_date FROM public.finance_expenses WHERE id = v_expense_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
  END IF;

  IF TG_OP IN ('INSERT', 'UPDATE') AND NEW.finance_expense_id IS NOT NULL THEN
    v_expense_id := NEW.finance_expense_id;
    PERFORM 1 FROM public.finance_expenses fe
    WHERE fe.id = v_expense_id
      AND (COALESCE(fe.pph_amount, 0) > 0 OR COALESCE(fe.pib_pph_amount, 0) > 0 OR fe.expense_category = 'pph_import');
    IF NOT FOUND THEN
      v_expense_id := NULL;
    END IF;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') AND v_expense_id IS NOT NULL THEN
    v_voucher_id := NEW.payment_voucher_id;
    SELECT voucher_date INTO v_date FROM public.payment_vouchers WHERE id = v_voucher_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
    PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(v_expense_id));
    SELECT COALESCE(due_date, expense_date) INTO v_date FROM public.finance_expenses WHERE id = v_expense_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_recompute_pph_from_voucher_allocation ON public.voucher_allocations;
CREATE TRIGGER trg_recompute_pph_from_voucher_allocation
AFTER INSERT OR UPDATE OR DELETE ON public.voucher_allocations
FOR EACH ROW EXECUTE FUNCTION public.trg_recompute_pph_from_voucher_allocation();

CREATE OR REPLACE FUNCTION public.trg_recompute_pph_from_bank_line()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expense_id uuid;
  v_date date;
BEGIN
  IF TG_OP IN ('UPDATE', 'DELETE') AND OLD.matched_expense_id IS NOT NULL THEN
    v_expense_id := OLD.matched_expense_id;
    PERFORM 1 FROM public.finance_expenses fe
    WHERE fe.id = v_expense_id
      AND (COALESCE(fe.pph_amount, 0) > 0 OR COALESCE(fe.pib_pph_amount, 0) > 0 OR fe.expense_category = 'pph_import');
    IF NOT FOUND THEN
      v_expense_id := NULL;
    END IF;
  END IF;
  IF TG_OP IN ('UPDATE', 'DELETE') AND v_expense_id IS NOT NULL THEN
    PERFORM public.recompute_pph_periods_for_date(OLD.transaction_date);
    PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(v_expense_id));
    SELECT COALESCE(due_date, expense_date) INTO v_date FROM public.finance_expenses WHERE id = v_expense_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
  END IF;

  IF TG_OP IN ('INSERT', 'UPDATE') AND NEW.matched_expense_id IS NOT NULL THEN
    v_expense_id := NEW.matched_expense_id;
    PERFORM 1 FROM public.finance_expenses fe
    WHERE fe.id = v_expense_id
      AND (COALESCE(fe.pph_amount, 0) > 0 OR COALESCE(fe.pib_pph_amount, 0) > 0 OR fe.expense_category = 'pph_import');
    IF NOT FOUND THEN
      v_expense_id := NULL;
    END IF;
  END IF;
  IF TG_OP IN ('INSERT', 'UPDATE') AND v_expense_id IS NOT NULL THEN
    PERFORM public.recompute_pph_periods_for_date(NEW.transaction_date);
    PERFORM public.recompute_pph_periods_for_date(public.get_expense_pph_period_date(v_expense_id));
    SELECT COALESCE(due_date, expense_date) INTO v_date FROM public.finance_expenses WHERE id = v_expense_id;
    PERFORM public.recompute_pph_periods_for_date(v_date);
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_recompute_pph_from_bank_line ON public.bank_statement_lines;
CREATE TRIGGER trg_recompute_pph_from_bank_line
AFTER INSERT OR DELETE OR UPDATE OF matched_expense_id, transaction_date, payment_kind
ON public.bank_statement_lines
FOR EACH ROW EXECUTE FUNCTION public.trg_recompute_pph_from_bank_line();

-- Create any newly required destination months, then recalculate derived
-- Register snapshots only.  Source documents, allocations, bank links,
-- journals, tax payments, and filings are not modified.
DO $$
DECLARE
  v_date date;
  v_period_id uuid;
BEGIN
  FOR v_date IN
    SELECT DISTINCT public.get_expense_pph_period_date(fe.id)
    FROM public.finance_expenses fe
    WHERE fe.approval_status = 'approved'
      AND (
        COALESCE(fe.pph_amount, 0) > 0
        OR COALESCE(fe.pib_pph_amount, 0) > 0
        OR fe.expense_category = 'pph_import'
      )
  LOOP
    PERFORM public.recompute_pph_periods_for_date(v_date);
  END LOOP;

  FOR v_period_id IN
    SELECT id FROM public.tax_periods WHERE tax_type <> 'PPN'
  LOOP
    PERFORM public.compute_period_ppn(v_period_id);
  END LOOP;
END;
$$;

NOTIFY pgrst, 'reload schema';
