-- Record the official Faktur Pajak returned by the external CA.
-- Legacy statuses remain accepted so existing rows can be read safely, while
-- all new records use `recorded` and the UI maps legacy values to business
-- language.
ALTER TABLE public.faktur_pajak
  ADD COLUMN IF NOT EXISTS official_djp_number varchar(50),
  ADD COLUMN IF NOT EXISTS linked_invoice_id uuid REFERENCES public.sales_invoices(id),
  ADD COLUMN IF NOT EXISTS invoice_amount numeric(18,2),
  ADD COLUMN IF NOT EXISTS uploaded_by uuid REFERENCES auth.users(id),
  ADD COLUMN IF NOT EXISTS uploaded_at timestamptz;

UPDATE public.faktur_pajak
SET official_djp_number = COALESCE(official_djp_number, faktur_number),
    linked_invoice_id = COALESCE(linked_invoice_id, sales_invoice_id),
    invoice_amount = COALESCE(invoice_amount, dpp_amount + ppn_amount),
    uploaded_at = COALESCE(uploaded_at, updated_at)
WHERE official_djp_number IS NULL
   OR linked_invoice_id IS NULL
   OR invoice_amount IS NULL
   OR uploaded_at IS NULL;

ALTER TABLE public.faktur_pajak
  DROP CONSTRAINT IF EXISTS faktur_pajak_status_check;

ALTER TABLE public.faktur_pajak
  ADD CONSTRAINT faktur_pajak_status_check
  CHECK (status IN ('waiting','recorded','reported','cancelled','generated','uploaded'));

COMMENT ON COLUMN public.faktur_pajak.official_djp_number IS 'Official DJP number received from the external CA; never generated by the ERP.';
COMMENT ON COLUMN public.faktur_pajak.linked_invoice_id IS 'Explicit audit link to the originating Sales Invoice.';

UPDATE public.notifications
SET title = 'Waiting for Faktur',
    message = replace(message, 'Faktur Pajak missing', 'Waiting for Faktur')
WHERE type = 'faktur_missing';
