-- Complete the canonical batch/order response shape; report-only.
BEGIN;
CREATE OR REPLACE FUNCTION public.get_sales_profitability_batch_orders(p_batch_id uuid,p_start_date date,p_end_date date)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public,pg_temp AS $$
WITH x AS (
 SELECT ar.line_id,ar.invoice_id,si.invoice_number,si.invoice_date,si.customer_id,COALESCE(c.company_name,'Unknown Customer') customer_name,si.sales_order_id,so.so_number,dci.challan_id dc_id,dc.challan_number dc_number,ar.quantity,sii.unit_price selling_price,ROUND(ar.quantity*sii.unit_price,2) gross_sales,ar.authoritative_unit_cogs unit_cost,ar.authoritative_cogs line_cost,COALESCE(le.sales_expense,0) line_sales_expense,ar.resolution_tier cogs_resolution
 FROM public.get_authoritative_sales_line_cogs(p_start_date,p_end_date) ar JOIN public.sales_invoice_items sii ON sii.id=ar.line_id JOIN public.sales_invoices si ON si.id=ar.invoice_id LEFT JOIN public.customers c ON c.id=si.customer_id LEFT JOIN public.sales_orders so ON so.id=si.sales_order_id LEFT JOIN public.delivery_challan_items dci ON dci.id=sii.delivery_challan_item_id LEFT JOIN public.delivery_challans dc ON dc.id=dci.challan_id LEFT JOIN public.get_sales_profitability_line_expenses(p_start_date,p_end_date) le ON le.line_id=ar.line_id WHERE ar.batch_id=p_batch_id
), ex AS (SELECT fe.delivery_challan_id dc_id,jsonb_agg(jsonb_build_object('id',fe.id,'voucher_number',fe.voucher_number,'category',fe.expense_category,'total_amount',fe.amount,'description',fe.description,'expense_date',fe.expense_date)) expenses FROM public.finance_expenses fe WHERE fe.expense_category IN ('delivery_sales','loading_sales') AND fe.approval_status='approved' AND fe.delivery_challan_id IN (SELECT DISTINCT dc_id FROM x WHERE dc_id IS NOT NULL) GROUP BY fe.delivery_challan_id)
SELECT jsonb_build_object('batch',(SELECT jsonb_build_object('batch_id',b.id,'batch_number',b.batch_number,'product_name',p.product_name,'product_code',COALESCE(p.product_code,''),'product_unit',COALESCE(p.unit,'kg'),'current_stock',b.current_stock) FROM public.batches b JOIN public.products p ON p.id=b.product_id WHERE b.id=p_batch_id),'orders',COALESCE((SELECT jsonb_agg(jsonb_build_object('line_id',x.line_id,'invoice_id',x.invoice_id,'invoice_number',x.invoice_number,'invoice_date',x.invoice_date,'customer_id',x.customer_id,'customer_name',x.customer_name,'sales_order_id',x.sales_order_id,'so_number',x.so_number,'dc_id',x.dc_id,'dc_number',x.dc_number,'quantity',x.quantity,'selling_price',x.selling_price,'unit_price',x.selling_price,'gross_sales',x.gross_sales,'unit_cost',x.unit_cost,'line_cost',x.line_cost,'line_sales_expense',x.line_sales_expense,'net_selling_realization',x.gross_sales-x.line_sales_expense,'gross_profit',CASE WHEN x.line_cost IS NULL THEN NULL ELSE x.gross_sales-x.line_cost END,'profit',CASE WHEN x.line_cost IS NULL THEN NULL ELSE x.gross_sales-x.line_cost-x.line_sales_expense END,'profit_margin_pct',CASE WHEN x.line_cost IS NULL OR x.gross_sales=0 THEN NULL ELSE ROUND((x.gross_sales-x.line_cost-x.line_sales_expense)/x.gross_sales*100,2) END,'cogs_resolution',x.cogs_resolution,'expenses',COALESCE(ex.expenses,'[]'::jsonb)) ORDER BY x.invoice_date DESC,x.invoice_number) FROM x LEFT JOIN ex USING(dc_id)),'[]'::jsonb));
$$;
GRANT EXECUTE ON FUNCTION public.get_sales_profitability_batch_orders(uuid,date,date) TO authenticated;
COMMIT;
